# Generated by Django 3.0.4 on 2020-06-11 11:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numer_klienta', models.CharField(default=models.AutoField(primary_key=True), max_length=255)),
                ('Imię', models.CharField(max_length=255)),
                ('Nazwisko', models.CharField(max_length=255)),
                ('Numer_telefonu', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('Uwagi', models.TextField(default='Wprowadź uwagi')),
            ],
            options={
                'verbose_name_plural': 'Klienci',
            },
        ),
    ]
