# Generated by Django 3.0.4 on 2020-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyszukiwarka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienci',
            name='id',
        ),
        migrations.AlterField(
            model_name='klienci',
            name='Numer_klienta',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
