# Generated by Django 3.0.4 on 2020-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyszukiwarka', '0002_auto_20200611_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='Numer_klienta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
