# Generated by Django 3.0.4 on 2020-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyszukiwarka', '0003_auto_20200611_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='Numer_klienta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='Uwagi',
            field=models.TextField(null=True),
        ),
    ]
